VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :opensuse do |opensuse|
    opensuse.vm.box = "opensuse_kvm"

    opensuse.vm.provider :libvirt do |domain|
      domain.memory = 1024
      domain.cpus = 1
      domain.nested = false
      domain.volume_cache = 'none'
    end
  end
end
