VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :opensuse131 do |opensuse131|
    opensuse131.vm.box = "base_opensuse13.1_kvm"

    opensuse131.vm.provider :libvirt do |domain|
      domain.memory = 1024
      domain.cpus = 1
      domain.nested = false
      domain.volume_cache = 'none'
    end
  end
end
