Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/NegatedIf:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/Blocks:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/CollectionMethods:
  Enabled: false
