 packages:
   local:
     - curl            # Needed to download remote packages
     - iptables        # Needed by libvirt to configure network
     - dnsmasq         # Needed by libvirt to configure network
     - libxml2-devel   # Needed by libvirt plugin for Vagrant
     - libxslt-devel   # Needed by libvirt plugin for Vagrant
     - libvirt-devel   # Needed by libvirt plugin for Vagrant
     - libvirt         # Needed to run VMs
     - expect          # Needed to automate interactive commands like ssh-copy-id
   "13.1":
     - kvm                  # Needed to run VMs
     - libvirt-daemon-qemu  # Needed to run QEMU in 13.1
   "13.2":
     - qemu-kvm             # Needed to run VMs
   remote:
     - https://releases.hashicorp.com/vagrant/1.7.2/vagrant_1.7.2_x86_64.rpm
     
